name: b2b
channels:
  - pytorch
  - nvidia
  - huggingface
  - defaults
  - conda-forge
dependencies:
  - python=3.9.*
  - pip=21.2.*

  - pytorch=1.13.*
  # - cudatoolkit=11.7

  - nilearn=0.8.*
  - mne-bids=0.7

  - gensim=4.0.*
  - ngram=1.3.*
  - transformers=4.27.*
  - python-levenshtein=0.12.*

  - scipy=1.6.*
  - pandas=1.2.*
  - scikit-learn=1.2.*
  - scikit-learn-intelex=2021.5.*

  - wordcloud=1.8.*
  - matplotlib=3.6.*
  - seaborn=0.11.*

  - tqdm=4.61.*
  - ipywidgets=8.*
  - numba=0.55.*
  - line_profiler=3.*
  - montreal-forced-aligner=2.0.*

  - jupyterlab=3.1.*
  - jupyterlab_vim=0.15.*

  - pip:
    - himalaya==0.3.4
    # - empath==0.89
    - cupy==11.5.0
    - accelerate==0.15.0
